version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-nerdstore
        environment:
            RABBITMQ_DEFAULT_USER: "nerdstore"
            RABBITMQ_DEFAULT_PASS: "nerdstore"
        ports:
            - "5672:5672"
            - "15672:15672"    

    sql-server:
        image: nerdstore-sql-server:latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: nerdstore-web-mvc-ecommerce:latest
        container_name: nerdstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
        ports:
            - "5001:5001"
        restart: always            
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
#         volumes: 
#             - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-catalog
            - api-identity
            - api-client
            - api-bff-shopping

    api-identity:
        image: nerdstore-api-identity:latest
        container_name: nerdstore-api-identity    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Identity.API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            
    api-cart:
        image: nerdstore-api-cart:latest
        container_name: nerdstore-api-cart
        build: 
            context: ../src
            dockerfile: ./services/NSE.Cart.API/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server         

    api-catalog:
        image: nerdstore-api-catalog:latest
        container_name: nerdstore-api-catalog
        build: 
            context: ../src
            dockerfile: ./services/NSE.Catalog.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5301
        #     - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
        #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        # volumes:
        #     - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server

    api-client:
        image: nerdstore-api-client:latest
        container_name: nerdstore-api-client    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Client.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        # volumes:
        #     - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server  

    api-bff-shopping:
        image: nerdstore-api-bff-shopping:latest
        container_name: nerdstore-api-bff-shopping
        build: 
            context: ../src
            dockerfile: ./api gateways/NSE.Bff.Shopping/Dockerfile  
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            # - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        # volumes:
        #     - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-cart
            - api-payment
            - api-order
            
    api-payment:
        image: nerdstore-api-payment:latest
        container_name: nerdstore-api-payment    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Payement.API/Dockerfile
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5601;http://+5602
        #     - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
        #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        # volumes:
        #     - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-order
            - sql-server
            
    api-order:
        image: nerdstore-api-order:latest
        container_name: nerdstore-api-order    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Order.API/Dockerfile 
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5701;http://+5702
        #     - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
        #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        # volumes:
        #     - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            - api-identity                    

#     nerdstore-server:
#         image: desenvolvedorio/nerdstore-server:latest
#         container_name: nerdstore-server    
#         build: 
#             context: ./
#             dockerfile: ./nginx/Dockerfile 
#         restart: always 
#         ports:
#             - "80:80"
#             - "443:443"
#         depends_on:
#             - web-mvc

# volumes:
#     dpkeys:     